export const CUSTOMER_LOGIN_SUCCESS = 'CUSTOMER_LOGIN_SUCCESS';
export const CUSTOMER_LOGIN_FAILURE = 'CUSTOMER_LOGIN_FAILURE';

export const CUSTOMER_SIGNUP_SUCCESS = 'CUSTOMER_SIGNUP_SUCCESS';
export const CUSTOMER_SIGNUP_FAILURE = 'CUSTOMER_SIGNUP_FAILURE';

export const CUSTOMER_PROFILE_GET_SUCCESS = 'CUSTOMER_PROFILE_GET_SUCCESS';
export const CUSTOMER_PROFILE_GET_FAILED = 'CUSTOMER_PROFILE_GET_FAILED';

export const CUSTOMER_PROFILE_UPDATE_SUCCESS = 'CUSTOMER_PROFILE_UPDATE_SUCCESS';
export const CUSTOMER_PROFILE_UPDATE_FAILED = 'CUSTOMER_PROFILE_UPDATE_FAILED';
//export const  = '';

// Restaurant related events
export const RESTAURANT_LOGIN_SUCCESS = 'RESTAURANT_LOGIN_SUCCESS';
export const RESTAURANT_LOGIN_FAILURE = 'RESTAURANT_LOGIN_FAILURE';

export const RESTAURANT_SIGNUP_SUCCESS = 'RESTAURANT_SIGNUP_SUCCESS';
export const RESTAURANT_SIGNUP_FAILURE = 'RESTAURANT_SIGNUP_FAILURE';

export const RESTAURANT_PROFILE_GET_SUCCESS = 'RESTAURANT_PROFILE_GET_SUCCESS';
export const RESTAURANT_PROFILE_GET_FAILED = 'RESTAURANT_PROFILE_GET_FAILED';

export const RESTAURANT_PROFILE_UPDATE_SUCCESS = 'RESTAURANT_PROFILE_UPDATE_SUCCESS';
export const RESTAURANT_PROFILE_UPDATE_FAILED = 'RESTAURANT_PROFILE_UPDATE_FAILED';

export const LOGOUT = 'LOGOUT';


